name: Coverage

on:
  workflow_run:
    workflows: ["Test Laravel"]
    types:
      - completed 
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: PHPUnit (PHP ${{ matrix.php-versions }})
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Get Clover
      uses: actions/download-artifact@v2
      with:
        name: PHP Unit Clover
        path: build/logs/clover.xml
    - name: Get report
      run: |    
        composer global require php-coveralls/php-coveralls
        php-coveralls --coverage_clover=build/logs/clover.xml
        